config/routes.rb
Easyblog::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :posts do
    
    resources :comments do
      member do
        post :voteup
        post :votedown
        post :not_abusive
      end
    end
    
    member do
      post :mark_archived
    end
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :commenter, type: String
  field :users_vote, type: Array
  field :body, type: String
  field :voteup_count, type: Integer
  field :votedown_count, type: Integer
  field :abusive, type: Boolean, default: false
  field :user_id, type: String
  embedded_in :post
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Taggable

  field :body, type: String
  field :title, type: String
  field :user_id, type: String
  field :archived, type: Boolean, default: false

  validates_presence_of :body, :title

  belongs_to :user
  embeds_many :comments

  default_scope ne(archived: true)

  def archive!
    update_attribute :archived, true
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  validates_presence_of :email
  validates_presence_of :encrypted_password

  has_many :posts

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  index({ email: 1 }, { unique: true, background: true })
  validates :name, presence: true
  validates :nickname, uniqueness: true, if: proc { |u| u.nickname }
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :created_at, :updated_at, :nickname

  field :name, type: String
  field :nickname, type: String

  def owner? post
    posts.include? post
  end

  def to_s
    nickname.present? ? nickname : name
  end
end

app/models/vote.rb
class Vote
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      post = Post.find(params[:post_id])
      comment = post.comments.create(params[:comment])
      comment.commenter = User.name
      comment.voteup_count = 0
      comment.votedown_count = 0
      comment.users_vote = Array.new
      comment.user_id = current_user.id
      comment.save
      redirect_to post_path(post)
    end

    def destroy
      post = Post.find(params[:id])
      comment = post.comments.find(params[:post_id])
      comment.destroy
      redirect_to post_path(post)
    end

    def voteup
      post = Post.find(params[:id])
      comment = post.comments.find(params[:post_id])
      if !comment.users_vote.include?(current_user.id) 
        comment.users_vote << current_user.id
        comment.voteup_count += 1
        comment.save
        redirect_to post_path(post)
      else
        redirect_to post_path(post)
      end
    end

    def votedown
      post = Post.find(params[:id])
      comment = post.comments.find(params[:post_id])
      if !comment.users_vote.include?(current_user.id) 
        comment.users_vote << current_user.id
        comment.votedown_count += 1
        try_abusive()
        comment.save
        redirect_to post_path(post)
      else
        redirect_to post_path(post)
      end
    end

    def try_abusive
      post = Post.find(params[:id])
      comment = post.comments.find(params[:post_id])
      if comment.votedown_count >= 2
        comment.abusive = true
        comment.save
      end
    end

    def not_abusive
      post = Post.find(params[:id])
      comment = post.comments.find(params[:post_id])
      comment.abusive = false
      comment.save
      redirect_to post_path(post)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  expose_decorated(:posts)
  expose_decorated(:post)
  expose(:tag_cloud) { [] }

  def index
  end

  def new
  end

  def edit
  end

  def update
    if post.save
      render action: :index
    else
      render :new
    end
  end

  def destroy
    post.destroy if current_user.owner? post
    render action: :index
  end

  def show
  end

  def mark_archived
    post.archive!
    render action: :index
  end

  def create
    post.user_id = current_user.id
    if post.save
      redirect_to action: :index
    else
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def is? controller_name
    "active" if params[:controller] == "#{controller_name}"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Welcome to Netguru test application

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navigation
  %ul.nav
    %li
      = link_to "Easyblog", root_path
    - if user_signed_in?
      %li{class: is?("posts")}
        = link_to 'Posts', posts_path
      %li{class: is?("devise/registrations")}
        = link_to 'Edit account', edit_user_registration_path
      %li.logout-button
        = link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'pull-right'
    - else
      %li.login-button
        = link_to 'Login', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Easyblog"
      %meta{:content => content_for?(:description) ? yield(:description) : "Easyblog", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-inverse.navbar-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .span12
            = render 'layouts/messages'
        .row
          .span12.content-container
            = yield
          %footer

app/views/posts/_comment.haml
  .comment_new  
    = simple_form_for [ post, post.comments.build ], html: { class: "form-comment", style: "margin-top:80px;"} do |f|
      = f.input :commenter
      = f.input :body
      = f.button :submit

app/views/posts/_form.haml
= simple_form_for post, html: { class: "form-horizontal" } do |f|
  = f.input :title
  = f.input :body, as: :text, input_html: { cols: 50, rows: 3 }
  = f.input :tags, as: :text, hint: "comma separated values", input_html: { cols: 50, rows: 3 }
  = f.button :submit

app/views/posts/_tag_cloud.haml
- tag_cloud.each do |tag|
  %span.label
    = "#{tag[0]} (#{tag[1].to_i})"

app/views/posts/edit.haml
.page-header
  %h1 edit post

= render "form"

app/views/posts/index.haml
%h2 tags
= render partial: "tag_cloud", locals: { tag_cloud: tag_cloud }
%h2
  posts
  %small
    = "(#{posts.count})"
  = link_to "add new", new_post_path, class: 'post__button--add pull-right'

%ol
  - posts.each do |post|
    %li.post--short-size
      .post__title= link_to post.title, post_path(post)
      .post__body= post.truncated_body

app/views/posts/new.haml
%h2 new post

= render "form"

app/views/posts/show.haml
.post--full-size
  %h2
    = post.title
    %small
      = post.created_at.strftime("%d/%m/%Y : %H:%M")
  = link_to "edit", edit_post_path(post), class: 'post__button--edit'
  = post.user_id

  
  .post__body
    = post.body
  .post__tags-list.tagsinput
    - post.tags_array.each do |tag|
      = content_tag :span, tag, class: 'tag'

  .comment_display
    %h3 Komentarze
    - post.comments.each do |comment|
      - if !comment.abusive or post.user_id == current_user.id
        .comment_single
          %p
            %strong Napisany przez:
            = comment.commenter
          %p
            %strong Treść:
            = comment.body  
          .votes
            %strong Głosuj:
            = link_to "PLUS", voteup_post_comment_path(comment), method: :post
            =  comment.voteup_count 
            = link_to "MINUS", votedown_post_comment_path(comment), method: :post
            = comment.votedown_count
            - if comment.abusive
              = link_to "NOT ABUSIVE", not_abusive_post_comment_path(comment), method: :post,  :confirm => "Jesteś pewnien?"
          
            /= link_to "Delete Comment", [comment.post, comment], method: :delete  

  .comment_new  
    = simple_form_for [ post, post.comments.build ], html: { class: "form-comment", style: "margin-top:80px;"} do |f|
      = f.input :commenter
      = f.input :body
      = f.button :submit
  
  

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}